import { NobloxClient } from '../../../../client/noblox.js'

/** 
      * 🔓 Returns a list of thumbnails with varying types and sizes
      * 
 * @param client the inherited http client and noblox wrapper class
 * @param requests List of ThumbnailBatchRequest objects, may contain the following request types:
            1. Avatar
            2. AvatarHeadShot
            3. GameIcon
            4. BadgeIcon
            5. GameThumbnail
            6. GamePass
            7. Asset
            8. BundleThumbnail
            9. Outfit
            10. GroupIcon
            11. DeveloperProduct
            12. AutoGeneratedAsset
            13. AvatarBust
            14. PlaceIcon
 * @return OK TODO:
      */
export async function getBatchThumbnails(client: NobloxClient, requests: ThumbnailBatchRequest) {
  return await client.http<ThumbnailBatchResponse[]>(`https://thumbnails.roblox.com/v1/batch`, {
    method: 'POST',
    context: {
      authenticationLevel: 'OPTIONAL',
    },
    json: {
      requests,
    },
  })
}
