import { NobloxClient } from '../../../../client/noblox.js'

/**
 * 🔓 Thumbnails assets.
 *
 * @param client the inherited http client and noblox wrapper class
 * @param assetIds The asset ids.
 * @param returnPolicy Optional policy to use in selecting thumbnail to return (default = PlaceHolder).
 * @param size The thumbnail size, formatted widthxheight
 * @param format The thumbnail format
 * @param isCircular The circle thumbnail output parameter, true or false
 * @return OK TODO:
 */
export async function getAssetThumbnails(
  client: NobloxClient,
  assetIds: number[],
  returnPolicy?: 'PlaceHolder' | 'AutoGenerated' | 'ForceAutoGenerated',
  size:
    | '30x30'
    | '42x42'
    | '50x50'
    | '60x62'
    | '75x75'
    | '110x110'
    | '140x140'
    | '150x150'
    | '160x100'
    | '160x600'
    | '250x250'
    | '256x144'
    | '300x250'
    | '304x166'
    | '384x216'
    | '396x216'
    | '420x420'
    | '480x270'
    | '512x512'
    | '576x324'
    | '700x700'
    | '728x90'
    | '768x432' = '30x30',
  format: Png | Jpeg = Png,
  isCircular: boolean = false
) {
  return await client.http<ThumbnailResponse[]>(`https://thumbnails.roblox.com/v1/assets`, {
    method: 'GET',
    context: {
      authenticationLevel: 'OPTIONAL',
    },
    searchParams: {
      assetIds,
      returnPolicy,
      size,
      format,
      isCircular,
    },
  })
}
